# Generated by Django 4.2.7 on 2025-07-19 14:36

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="receipts/")),
                ("vendor", models.CharField(db_index=True, max_length=200)),
                ("transaction_date", models.DateField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("internet", "Internet"),
                            ("groceries", "Groceries"),
                            ("restaurant", "Restaurant"),
                            ("shopping", "Shopping"),
                            ("transportation", "Transportation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("raw_text", models.TextField(blank=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "transaction_date"],
                        name="receipts_re_vendor_4f1dc2_idx",
                    ),
                    models.Index(
                        fields=["amount", "transaction_date"],
                        name="receipts_re_amount_5f0b14_idx",
                    ),
                    models.Index(
                        fields=["category", "transaction_date"],
                        name="receipts_re_categor_f9c3ef_idx",
                    ),
                ],
            },
        ),
    ]
