# Generated by Django 4.2.7 on 2025-07-19 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receipt",
            options={
                "ordering": ["-transaction_date", "-created_at"],
                "verbose_name": "Receipt",
                "verbose_name_plural": "Receipts",
            },
        ),
        migrations.AlterField(
            model_name="receipt",
            name="amount",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                help_text="Amount in INR",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
